# copy of https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
on: [push, pull_request]

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: check

  test:
    name: Test Suite
    if: ${{ !startsWith(github.event.pull_request.title, '[WIP]') }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # macos-latest might be readded later
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: build
      - uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: test


  lints:
    name: Rust lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: clippy
          args: -- --deny warnings
